### ISSUE TITLE
Wrong options for docker run in the Docker Hub's description

### ISSUE THREAD

**Issue by kazusato** [payara/docker-payaramicro#20]
This is not an issue to the Docker image itself but to a description on Docker Hub (https://hub.docker.com/r/payara/micro/).

In the QuickStart section,
I can see the following command to run its container:
> docker run -p 8080:8080 payara/micro java -jar /opt/payara/payara-micro.jar

However, its Dockerfile has an ENTRYPOINT as follows:
ENTRYPOINT ["java", "-jar", "/opt/payara/payara-micro.jar"]

and I think it should be:
> docker run -p 8080:8080 payara/micro 

(README.md in this repository is correct.)

**Comment by OndrejM** [comment]
Thanks for raising this. Dockerhub shows the README from the recent build, which is not always from master. I synchronized README to other branches so that Dockerhub always displays the same description.
