### ISSUE TITLE
Allow specifying context root via an ENV variable

### ISSUE THREAD

**Issue by OndroMih** [payara/docker-payaramicro#25]
Context root can be specified if apps are deployed using asadmin deploy in a `--postbootcommandfile` script as suggested here: https://stackoverflow.com/a/51360858/784594

Add option to specify a CONTEXT_ROOT env var and deploy using asadmin command if that var is specified.

**Comment by smillidge** [comment]
superseded in later payara micro verions by `--contextroot`
