### ISSUE TITLE
Document how to deploy to context root / (PYSVC-849)

### ISSUE THREAD

**Issue by brunoborges** [payara/docker-payaramicro#26]
Please document in the README of this image (that shows on https://hub.docker.com/r/payara/micro/) on how to deploy a WAR/EAR into context-root.

What worked for me was deploying a war file renamed to ROOT.war:

```Dockerfile
FROM payara/micro:5.182
COPY target/myapp.war $DEPLOY_DIR/ROOT.war
EXPOSE 8080
```

**Comment by OndrejM** [comment]
Hi, @brunoborges, this is currently the only way to do it - the context root is derived from the file name and if it's ROOT, then the context root becomes "/".

This is already document here: https://docs.payara.fish/documentation/payara-micro/configuring/package-uberjar.html. It also applies in other contexts not only uber JAR, although it's not clear.

We'll clarify this and add it to the docs of the docker container too.

**Comment by rdebusscher** [comment]
@brunoborges Since Payara Micro 5.191, there is the possibility to explicitly define the root on which the application is deployed.

See https://github.com/payara/docker-payaramicro#define-context-root

**Comment by brunoborges** [comment]
Sweet! Thanks guys. This simplifies as it becomes more natural and explicit.
