### ISSUE TITLE
latest tag pulling 5.184

### ISSUE THREAD

**Issue by AllenConquest** [payara/docker-payaramicro#39]
I did a pull on payara/micro and it ran version 5.184. When I pulled payara/micro:5.191 it pulled the current release. Is 5.191 the latest release or not?

**Comment by OndroMih** [comment]
Hi, this is a bug in our build system for docker images. 5.191 is the latest release, but the latest tag was incorrectly built from the 5.184 version. This affects also docker images for Payara Server Full and Web.

**Comment by MarkWareham** [comment]
Tracked internally with INFRA-236

**Comment by smillidge** [comment]
latest tag is pulling 5.192
