### ISSUE TITLE
Log issue

### ISSUE THREAD

**Issue by AbhideepChakravarty** [payara/docker-payaramicro#50]
Please refer https://github.com/payara/docker-payaraserver-full/issues/96

**Comment by OndroMih** [comment]
The property `fish.payara.enterprise.server.logging.stdio.disable` was renamed in 5.192 version. You should set `com.sun.enterprise.server.logging.GFFileHandler.logStandardStreams` property to `false` to disable capturing stdout.

**Comment by AbhideepChakravarty** [comment]
Is it same in 5.193  (Just in case, I move to 193)?
