### ISSUE TITLE
Image size increase over 100 mb from 5.192 to 5.193

### ISSUE THREAD

**Issue by Herr-Sepp** [payara/docker-payaramicro#52]
The docker image size is now 293 MB from 184 MB (5.192). Which is a increase more then 50% and i think this is problemetic for a microservices baseimage.

I found out that the JDK change from "openjdk:8-jdk-alpine" to  "azul/zulu-openjdk-alpine:8u212" is responsible for this enlargement.(#42 )
(5.193 with openJDK is ~185 MB)

But i'm not sure why it is so much.
Openjdk-image ~ 71 MB
zulu-openjdk-image ~ 105 MB

The JDK-baseimages dont have that much difference in size, that can explane the whole increase. 

Would be great if you cloud look into it to make the image size again around 200 MB.

**Comment by OndroMih** [comment]
When I run `docker images`, I see that the Zulu image is 213MB and not 105MB as you claim:

```
azul/zulu-openjdk-alpine                                      8u212                   b241474b99a5        5 months ago        213MB
```

That explains the difference in size.

Dockerhub claims the image size is 103.45MB. When I compare the digest, the one I get with `docker pull azul/zulu-openjdk-alpine:8u212` is different than the one I see in Dockerhub. I don't understand what happened and why the actual docker image on my computer is twice as big as it's supposed to be.

**Comment by OndroMih** [comment]
I think I know what all those numbers mean. The number 103.45MB reported by docker hub is the size of the compressed image. The number reported by `docker images` is the actual size of the image. I tried removing all the docker images on my computer and ran `azul/zulu-openjdk-alpine:8u212`. That command showed it's downloading around 100 MB of data. But then `docker images` still shows the size of the image is 213MB.

However, Azul also offers JRE versions of Docker images. And the image tagged 8u212-jre has 113MB. Payara Micro doesn't need a JDK to run so we can replace the base image to use a JRE image.

**Comment by OndroMih** [comment]
I've created #53 to use JRE base images.

**Comment by Herr-Sepp** [comment]
I was also unaware that Dockerhub only displays the compressed size of an image. Thanks for the research, and the use of JRE is a great idea.

Zulu's JRE is not as much bigger than the OpenJDK-jre anymore.
Nevertheless there is still a difference of 25 mb between zulu vs. openjdk -JRE. Are there any disadvantages if I don't use Zulu?

And is there a reason why you don't use 8u222 instead of 8u212?

**Comment by Herr-Sepp** [comment]
ok so i found out that OpenJDK will not support JDK/JRE builds beyond 8u212 with a alpine base image:
> "no more OpenJDK 8 Alpine images (Alpine/musl is not officially supported by the OpenJDK project,"

see https://github.com/docker-library/openjdk/issues/272 or https://github.com/docker-library/openjdk/pull/322

And all other Java Runtime Images:
- amazoncorretto
- adoptopenjdk
- ibmjava

does not have a alpine image, so that all are bigger then Zulu. 

For now the best choice is Zulu, thank you for your help. 
I will close the Issue.
