### ISSUE TITLE
prerelease is not a "nightly build of Payara Micro", its from 08.2018

### ISSUE THREAD

**Issue by Herr-Sepp** [payara/docker-payaramicro#55]
I wanted to test the new support for alternate opentracing Implementation (https://github.com/payara/Payara/pull/4239 PAYARA-3263) and hoped i can do that with the "prerelease" Docker image tag.

But the Payara version on this image is from 08.2018.

Why you build a new image daily with this old version of payara and with an outdatet buildfile ;)

**Comment by OndroMih** [comment]
Thanks for raising this. Our build is misconfigured and we didn't notice. This should fix it the next day after it's merged: #56.

**Comment by Herr-Sepp** [comment]
Thanks for fixing this, but can you also update the buildfile to match the master state?
There were some importent commits in the last year for example the docker memory management and revealing the correct ports.
