### ISSUE TITLE
Run docker image payara/micro:5.194, log displays Payara Micro 5.193

### ISSUE THREAD

**Issue by teerakorn** [payara/docker-payaramicro#58]
When starting docker image of payara/micro:5.194 with the following command

"docker run -p 8080:8080 payara/micro:5.194"

We see that log displays Payara Micro 5.193. 
It looks like PAYARA_VERSION in Dockerfile needs to be updated to 5.194? (https://hub.docker.com/layers/payara/micro/5.194/images/sha256-ca9e7651639a63af8ec2b0a7e5761e4f7ef498175cfa6568dc33fac89e69418b)

**Comment by rdebusscher** [comment]
Hi @teerakorn,

Is this still the case?

can you perform the following commands

```
docker pull payara/micro:5.194
docker run -p 8080:8080 payara/micro:5.194
```

Thx 
Regards
Rudy

**Comment by fturizo** [comment]
Closing this issue as this repository is to be archived. Support for new docker images of Payara Micro Community will be handled in the main repository: https://github.com/payara/Payara. Raise this issue there if this is the case.
