### ISSUE TITLE
The java base container is deprecated

### ISSUE THREAD

**Issue by tiainen** [payara/docker-payaramicro#7]
According to the [java container](https://hub.docker.com/_/java/) page at docker hub, that image is deprecated and superseded by the [openjdk container](https://hub.docker.com/_/openjdk/). In order to keep up with newer releases op Open JDK, it would be better to base the Payara Micro docker container on `openjdk:8-jdk-alpine`.

**Comment by mikecroft** [comment]
Thanks for the update! We'll get the base container changed as soon as we can.

**Comment by mikecroft** [comment]
internal issue `PYSVC-375`

**Comment by mikecroft** [comment]
fixed by #12
